"""empty message

Revision ID: 13b94e513fe5
Revises: 6a7547df90d4
Create Date: 2021-02-26 23:07:54.575319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13b94e513fe5'
down_revision = '6a7547df90d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Planetas_props')
    op.drop_table('Personajes_props')
    op.add_column('Personajes', sa.Column('altura', sa.String(length=250), nullable=True))
    op.add_column('Personajes', sa.Column('color_cabello', sa.String(length=250), nullable=True))
    op.add_column('Personajes', sa.Column('creacion', sa.String(length=250), nullable=True))
    op.add_column('Personajes', sa.Column('editado', sa.String(length=250), nullable=True))
    op.add_column('Personajes', sa.Column('fecha_nacimiento', sa.String(length=250), nullable=True))
    op.add_column('Personajes', sa.Column('genero', sa.String(length=250), nullable=True))
    op.add_column('Personajes', sa.Column('imagen', sa.String(length=250), nullable=True))
    op.add_column('Personajes', sa.Column('masa', sa.String(length=250), nullable=True))
    op.add_column('Personajes', sa.Column('mundo_origen', sa.String(length=250), nullable=True))
    op.add_column('Personajes', sa.Column('ojos', sa.String(length=250), nullable=True))
    op.add_column('Personajes', sa.Column('piel', sa.String(length=250), nullable=True))
    op.drop_column('Personajes', 'url')
    op.add_column('Planetas', sa.Column('clima', sa.String(length=250), nullable=True))
    op.add_column('Planetas', sa.Column('diametro', sa.String(length=250), nullable=True))
    op.add_column('Planetas', sa.Column('gravedad', sa.String(length=250), nullable=True))
    op.add_column('Planetas', sa.Column('imagen', sa.String(length=250), nullable=True))
    op.add_column('Planetas', sa.Column('periodo_orbital', sa.String(length=250), nullable=True))
    op.add_column('Planetas', sa.Column('periodo_rotacion', sa.String(length=250), nullable=True))
    op.add_column('Planetas', sa.Column('poblacion', sa.String(length=250), nullable=True))
    op.add_column('Planetas', sa.Column('residentes', sa.String(length=250), nullable=True))
    op.add_column('Planetas', sa.Column('superficie_acuatica', sa.String(length=250), nullable=True))
    op.add_column('Planetas', sa.Column('terreno', sa.String(length=250), nullable=True))
    op.drop_column('Planetas', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Planetas', sa.Column('url', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('Planetas', 'terreno')
    op.drop_column('Planetas', 'superficie_acuatica')
    op.drop_column('Planetas', 'residentes')
    op.drop_column('Planetas', 'poblacion')
    op.drop_column('Planetas', 'periodo_rotacion')
    op.drop_column('Planetas', 'periodo_orbital')
    op.drop_column('Planetas', 'imagen')
    op.drop_column('Planetas', 'gravedad')
    op.drop_column('Planetas', 'diametro')
    op.drop_column('Planetas', 'clima')
    op.add_column('Personajes', sa.Column('url', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('Personajes', 'piel')
    op.drop_column('Personajes', 'ojos')
    op.drop_column('Personajes', 'mundo_origen')
    op.drop_column('Personajes', 'masa')
    op.drop_column('Personajes', 'imagen')
    op.drop_column('Personajes', 'genero')
    op.drop_column('Personajes', 'fecha_nacimiento')
    op.drop_column('Personajes', 'editado')
    op.drop_column('Personajes', 'creacion')
    op.drop_column('Personajes', 'color_cabello')
    op.drop_column('Personajes', 'altura')
    op.create_table('Personajes_props',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('altura', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('masa', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('color_cabello', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('piel', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('ojos', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('fecha_nacimiento', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('genero', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('creacion', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('editado', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('nombre', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('mundo_origen', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('personajes_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imagen', mysql.VARCHAR(length=250), nullable=True),
    sa.ForeignKeyConstraint(['personajes_id'], ['Personajes.id'], name='Personajes_props_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Planetas_props',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clima', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('diametro', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('gravedad', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('nombre', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('periodo_orbital', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('poblacion', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('residentes', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('periodo_rotacion', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('superficie_acuatica', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('terreno', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('planetas_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imagen', mysql.VARCHAR(length=250), nullable=True),
    sa.ForeignKeyConstraint(['planetas_id'], ['Planetas.id'], name='Planetas_props_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
