"""empty message

Revision ID: 2e4db47fd94b
Revises: 9a5b3bcd8398
Create Date: 2021-02-26 17:18:51.461505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e4db47fd94b'
down_revision = '9a5b3bcd8398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'id_usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('id_usuario', mysql.VARCHAR(length=250), nullable=False))
    # ### end Alembic commands ###
