"""empty message

Revision ID: 4b2cebec0017
Revises: 
Create Date: 2021-03-02 15:26:03.451568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2cebec0017'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.Column('altura', sa.String(length=250), nullable=True),
    sa.Column('masa', sa.String(length=250), nullable=True),
    sa.Column('color_cabello', sa.String(length=250), nullable=True),
    sa.Column('piel', sa.String(length=250), nullable=True),
    sa.Column('ojos', sa.String(length=250), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(length=250), nullable=True),
    sa.Column('genero', sa.String(length=250), nullable=True),
    sa.Column('creacion', sa.String(length=250), nullable=True),
    sa.Column('editado', sa.String(length=250), nullable=True),
    sa.Column('mundo_origen', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.Column('clima', sa.String(length=250), nullable=True),
    sa.Column('diametro', sa.String(length=250), nullable=True),
    sa.Column('gravedad', sa.String(length=250), nullable=True),
    sa.Column('periodo_orbital', sa.String(length=250), nullable=True),
    sa.Column('poblacion', sa.String(length=250), nullable=True),
    sa.Column('residentes', sa.String(length=250), nullable=True),
    sa.Column('periodo_rotacion', sa.String(length=250), nullable=True),
    sa.Column('superficie_acuatica', sa.String(length=250), nullable=True),
    sa.Column('terreno', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('planetas_id', sa.Integer(), nullable=True),
    sa.Column('personajes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['personajes_id'], ['Personajes.id'], ),
    sa.ForeignKeyConstraint(['planetas_id'], ['Planetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Favoritos')
    op.drop_table('User')
    op.drop_table('Planetas')
    op.drop_table('Personajes')
    # ### end Alembic commands ###
