"""empty message

Revision ID: 6a7547df90d4
Revises: 8dd262c28720
Create Date: 2021-02-26 17:58:56.186456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7547df90d4'
down_revision = '8dd262c28720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Personajes_props', sa.Column('imagen', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Personajes_props', 'imagen')
    # ### end Alembic commands ###
