"""empty message

Revision ID: 8dd262c28720
Revises: 2e4db47fd94b
Create Date: 2021-02-26 17:57:56.181601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd262c28720'
down_revision = '2e4db47fd94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Planetas_props', sa.Column('imagen', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Planetas_props', 'imagen')
    # ### end Alembic commands ###
