"""empty message

Revision ID: 9a5b3bcd8398
Revises: 762402052503
Create Date: 2021-02-26 17:15:56.505746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a5b3bcd8398'
down_revision = '762402052503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('lastname', sa.String(length=250), nullable=False),
    sa.Column('id_usuario', sa.String(length=250), nullable=False),
    sa.Column('contraseña', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('planetas_id', sa.Integer(), nullable=True),
    sa.Column('personajes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['personajes_id'], ['Personajes.id'], ),
    sa.ForeignKeyConstraint(['planetas_id'], ['Planetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Personajes_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('altura', sa.String(length=250), nullable=True),
    sa.Column('masa', sa.String(length=250), nullable=True),
    sa.Column('color_cabello', sa.String(length=250), nullable=True),
    sa.Column('piel', sa.String(length=250), nullable=True),
    sa.Column('ojos', sa.String(length=250), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(length=250), nullable=True),
    sa.Column('genero', sa.String(length=250), nullable=True),
    sa.Column('creacion', sa.String(length=250), nullable=True),
    sa.Column('editado', sa.String(length=250), nullable=True),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('mundo_origen', sa.String(length=250), nullable=True),
    sa.Column('personajes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personajes_id'], ['Personajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Planetas_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clima', sa.String(length=250), nullable=True),
    sa.Column('diametro', sa.String(length=250), nullable=True),
    sa.Column('gravedad', sa.String(length=250), nullable=True),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('periodo_orbital', sa.String(length=250), nullable=True),
    sa.Column('poblacion', sa.String(length=250), nullable=True),
    sa.Column('residentes', sa.String(length=250), nullable=True),
    sa.Column('periodo_rotacion', sa.String(length=250), nullable=True),
    sa.Column('superficie_acuatica', sa.String(length=250), nullable=True),
    sa.Column('terreno', sa.String(length=250), nullable=True),
    sa.Column('planetas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planetas_id'], ['Planetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('email', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`is_active` in (0,1))', name='user_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_table('Planetas_props')
    op.drop_table('Personajes_props')
    op.drop_table('Favoritos')
    op.drop_table('User')
    op.drop_table('Planetas')
    op.drop_table('Personajes')
    # ### end Alembic commands ###
