"""empty message

Revision ID: ba4f6e4c4841
Revises: 4eedd338cd94
Create Date: 2021-03-01 22:51:50.247285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba4f6e4c4841'
down_revision = '4eedd338cd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.String(length=250), nullable=False))
    op.add_column('User', sa.Column('user', sa.String(length=250), nullable=False))
    op.drop_column('User', 'name')
    op.drop_column('User', 'contraseña')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('contraseña', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('User', sa.Column('name', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('User', 'user')
    op.drop_column('User', 'password')
    # ### end Alembic commands ###
